openapi: 3.0.1
info:
  title: Flatmates Search Plugin
  description: A plugin that allows the user to search for an ideal apartment using ChatGPT.
  version: 'v1'
servers:
  - url: https://openai-flatmates-search.onrender.com
paths:
  /:
    get:
      operationId: getRentalsFlatmates
      summary: Get a list of available rentals in the area the user is searching using flatmates.com.au.
      parameters:
        - in: query
          name: locations
          schema:
            type: string
          required: false
          description: The location of the rental property, formatted as suburb-postcode. e.g. "penrith-2750"
        - in: query
          name: bathroomType
          schema:
            type: string
          required: false
          description: The type of bathroom in the rental property. Options are "ensuite-or-own" or "ensuite"
        - in: query
          name: furnishings
          schema:
            type: string
          required: false
          description: The furnishings of the rental property. Options are "furnished" or "unfurnished"
        - in: query
          name: parking
          schema:
            type: string
          required: false
          description: The parking requirements for the rental property. Options are "off-street-parking" or "on-street-parking"
        - in: query
          name: gender
          schema:
            type: string
          required: false
          description: The gender preference for the rental property. Options are "male", "female" or "couples"
        - in: query
          name: allFemale
          schema:
            type: boolean
          required: false
          description: Whether the rental property is all-female
        - in: query
          name: lengthOfStay
          schema:
            type: integer
          required: false
          description: The desired length of stay in weeks, months or years. e.g. "1 year"
        - in: query
          name: lgbtFriendly
          schema:
            type: boolean
          required: false
          description: Whether the rental property is LGBT-friendly
        - in: query
          name: retirees
          schema:
            type: boolean
          required: false
          description: Whether the rental property is suitable for retirees
        - in: query
          name: students
          schema:
            type: boolean
          required: false
          description: Whether the rental property is suitable for students
        - in: query
          name: smokers
          schema:
            type: boolean
          required: false
          description: Whether the rental property allows smoking
        - in: query
          name: backpackers
          schema:
            type: boolean
          required: false
          description: Whether the rental property is suitable for backpackers
        - in: query
          name: children
          schema:
            type: boolean
          required: false
          description: Whether the rental property is suitable for children
        - in: query
          name: over40
          schema:
            type: boolean
          required: false
          description: Whether the rental property is suitable for people over 40
        - in: query
          name: pets
          schema:
            type: boolean
          required: false
          description: Whether the rental property allows pets
        - in: query
          name: numberOfRooms
          schema:
            type: integer
          required: false
          description: The number of rooms required
        - in: query
          name: room
          schema:
            type: string
          required: false
          description: The type of room. Options are private-room and shared-room
        - in: query
          name: shareHouses
          schema:
            type: boolean
          required: false
          description: Whether to include share houses in the rental properties
        - in: query
          name: dateAvailable
          schema:
            type: string
          required: false
          description: The date the rental property is available, formatted as day-month-year. e.g. "03-06-2023"
        - in: query
          name: minBudget
          schema:
            type: integer
          required: false
          description: The minimum budget for the rental property
        - in: query
          name: maxBudget
          schema:
            type: integer
          required: false
          description: The maximum budget for the rental property
        - in: query
          name: billsIncluded
          schema:
            type: boolean
          required: false
          description: Whether bills are included in the price of the rental property
        - in: query
          name: keywordInput
          schema:
            type: boolean
          required: false
          description: Keywords for the rental property search
        - in: query
          name: wholeProperties
          schema:
            type: boolean
          required: false
          description: Whether to include whole properties in the search
        - in: query
          name: studios
          schema:
            type: boolean
          required: false
          description: Whether to include studios in the search
        - in: query
          name: oneBeds
          schema:
            type: boolean
          required: false
          description: Whether to include 1-bedroom properties in the search
        - in: query
          name: grannyFlats
          schema:
            type: boolean
          required: false
          description: Whether to include granny flats in the search
        - in: query
          name: studentAccommodation
          schema:
            type: boolean
          required: false
          description: Whether to include student accommodations in the search
        - in: query
          name: homestays
          schema:
            type: boolean
          required: false
          description: Whether to include homestays in the search
        - in: query
          name: images
          schema:
            type: integer
          required: false
          description: Set to 0 to disable image results or any other number to set how many images per result to return. Default value is 2
        - in: query
          name: descriptionLength
          schema:
            type: integer
          required: false
          description: Set to 0 to disable desciption results or any other number to set the amount of characters to trim the description down to. Default value is 200
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getApartmentsResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The reason the request was rejected
components:
  schemas:
    getApartmentsResponse:
      type: object
      properties:
        nextPage:
          type: number
          description: The next page number for pagination
        listings:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
              images:
                type: array
                items:
                  type: string
              price:
                type: string
              billsIncluded:
                type: boolean
              bedrooms:
                type: number
              bathrooms:
                type: number
              occupants:
                type: number
              address:
                type: string
              rooms:
                type: string
              description:
                type: string