openapi: 3.0.1
info:
  title: Flatmates Search Plugin
  description: A plugin that allows the user to search for an ideal apartment using ChatGPT.
  version: 'v1'
servers:
  - url: https://openai-flatmates-search.onrender.com
paths:
  /:
    get:
      operationId: getRentalsFlatmates
      summary: Get a list of available rentals in the area the user is searching using flatmates.com.au.
      parameters:
        - in: query
          name: locations
          schema:
            type: string
          required: false
          description: The locations of the rental properties, formatted as suburb-postcode. Extras added with a + in between. e.g. "penrith-2750+parramatta-2150"
        - in: query
          name: locations
          schema:
            type: string
          required: false
          description: Locations required, formatted as suburb-postcode. Extras added with a + in between. e.g. "penrith-2750+parramatta-2150"
        - in: query
          name: page
          schema:
            type: string
          required: false
          description: page number to request
        - in: query
          name: bathroomType
          schema:
            type: string
          required: false
          description: Type of bathroom required. Options are "ensuite-or-own" or "ensuite"
        - in: query
          name: furnishings
          schema:
            type: string
          required: false
          description: Furnishings required. Options are "furnished" or "unfurnished"
        - in: query
          name: parking
          schema:
            type: string
          required: false
          description: Parking requirements. Options are "off-street-parking", "on-street-parking" or "no-parking"
        - in: query
          name: gender
          schema:
            type: string
          required: false
          description: Gender preference required. Options are "males", "females" or "couples"
        - in: query
          name: allFemale
          schema:
            type: boolean
          required: false
          description: Whether all female tenants are required
        - in: query
          name: lengthOfStay
          schema:
            type: string
          required: false
          description: Desired length of stay in weeks, months or years. e.g. "1 year"
        - in: query
          name: lgbtFriendly
          schema:
            type: boolean
          required: false
          description: Whether LGBT-friendly tenants are required
        - in: query
          name: retirees
          schema:
            type: boolean
          required: false
          description: Whether the property is suitable for retirees
        - in: query
          name: students
          schema:
            type: boolean
          required: false
          description: Whether the property is suitable for students
        - in: query
          name: smokers
          schema:
            type: boolean
          required: false
          description: Whether the property allows smoking
        - in: query
          name: backpackers
          schema:
            type: boolean
          required: false
          description: Whether the property is suitable for backpackers
        - in: query
          name: children
          schema:
            type: boolean
          required: false
          description: Whether the property is suitable for children
        - in: query
          name: over40
          schema:
            type: boolean
          required: false
          description: Whether the property is suitable for people over 40
        - in: query
          name: pets
          schema:
            type: boolean
          required: false
          description: Whether the property allows pets
        - in: query
          name: numberOfRooms
          schema:
            type: string
          required: false
          description: The number of rooms required
        - in: query
          name: room
          schema:
            type: string
          required: false
          description: The type of room. Options are private-room and shared-room
        - in: query
          name: shareHouses
          schema:
            type: boolean
          required: false
          description: Whether to include share houses in the listings
        - in: query
          name: dateAvailable
          schema:
            type: string
          required: false
          description: Date the rental property is available, formatted as day-month-year. e.g. "03-06-2023"
        - in: query
          name: minBudget
          schema:
            type: string
          required: false
          description: Minimum price for the property
        - in: query
          name: maxBudget
          schema:
            type: string
          required: false
          description: Maximum price for the property
        - in: query
          name: billsIncluded
          schema:
            type: boolean
          required: false
          description: Whether bills are included in the price
        - in: query
          name: keywordInput
          schema:
            type: string
          required: false
          description: Keywords to search in listing descriptions
        - in: query
          name: wholeProperties
          schema:
            type: boolean
          required: false
          description: Whether to include whole properties
        - in: query
          name: studios
          schema:
            type: boolean
          required: false
          description: Whether to include studios
        - in: query
          name: grannyFlats
          schema:
            type: boolean
          required: false
          description: Whether to include granny flats
        - in: query
          name: studentAccommodation
          schema:
            type: boolean
          required: false
          description: Whether to include student accommodations
        - in: query
          name: homestays
          schema:
            type: boolean
          required: false
          description: Whether to include homestays
        - in: query
          name: images
          schema:
            type: integer
          required: false
          description: Set to 0 to disable image results or any other number to set how many images per result to return. Default value is 2
        - in: query
          name: descriptionLength
          schema:
            type: integer
          required: false
          description: Set to 0 to disable desciption results or any other number to set the amount of characters to trim the description down to. Default value is 200
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getApartmentsResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The reason the request was rejected
components:
  schemas:
    getApartmentsResponse:
      type: object
      properties:
        nextPage:
          type: number
          description: The next page number for pagination
        listings:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: URL to the property listing. Start with the root server flatmates.com.au/ followed by this url.
              images:
                type: array
                items:
                  type: string
              price:
                type: string
              billsIncluded:
                type: boolean
              bedrooms:
                type: number
              bathrooms:
                type: number
              occupants:
                type: number
              address:
                type: string
              rooms:
                type: string
              description:
                type: string